import type { Metadata } from "next";
import "./globals.scss";
import TopNav from "@/components/topNav/page";
import Nav from "@/components/nav/page";
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <ThemeProvider>
          <Nav />
          <TopNav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
