import type { Metadata } from "next";
import { ThemeProvider } from "@/context/ThemeContext";
import TopNav from "@/components/topNav/page";
import Nav from "@/components/nav/page";

import "./globals.scss";

export const metadata: Metadata = {
  title: "paulovdev - portfolio",
  description: "Generated by create next app", 
  icons: {
    icon: '/photo.webp',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <ThemeProvider>
          <Nav />
          <TopNav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
